apiVersion: v1
kind: ReplicaSet
metadata:
  name: myapp-rc
  labels:
    app: myapp
    type: frontend
spec:
  replicas: <NUMBER OF REPLICAS>
  template:
    # Below here, you can resuse the content in pod-definition.yaml 
    metadata:
      name: myapp
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
  # ReplicaSet requires a selector key (in Replication Controller, it is optional)
  selector:
    matchLabels:
      type: front-end

