apiVersion: v1
kind: Service
metadata:
  name: back-end
spec:
  # Specify the type of service being created e.g Cluster IP, LoadBalancer, NodePort
  type: ClusterIP
  ports:
  - port: <Port>
    targetPort: <Target Port>
    nodePort: <Node Port>
  # The labels can be pulled from the pod definition yaml 
  selector:
    app: myapp
    type: back-end