AWSTemplateFormatVersion: "2010-09-09"
Description:
Resources:
  # RDS Instace dynamically referencing secrets manager
  MyRDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceClass: db.t2.micro
      Engine: MySQL
      EngineVersion: '5.7'
      MasterUsername: {{resolve:secretsmanager:mydb:SecretString:username}}}
      MasterUserPassword: {{resolve:secretsmanager:mydb:SecretString:password}}}
      DBName: mydb
      AllocatedStorage: '20'
      DBInstanceIdentifier: mydb
      PubliclyAccessible: 'true'
      StorageType: gp2
      VPCSecurityGroups:
        - !Ref MyDBSecurityGroup

  # Using SSM Secure String Parameter to store IAM User Password
  MyIAMUser:
    Type: AWS::IAM::User
    Properties:
      UserName: myuser
      LoginProfile:
        Password: {{resolve:ssm-secure:IAMUserPassword:1}}
      Policies:
        - PolicyName: mypolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'rds:*'
                Resource:
                  - !GetAtt MyRDSInstance.Arn
              - Effect: Allow
                Action:
                  - 'secretsmanager:*'
                Resource:
                  - !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:mydb*
                  - !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:myuser*
  # Using SSM Parameter (String type or StringList) to store Access Control
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: mybucket
      AccessControl: {{resolve:ssm:AccessControl:1}}
